### ISSUE TITLE
Develop post controllers

### ISSUE THREAD

**Issue by roenc576** [TenantVoice/TenantVoice#11]
Inside of the controllers directory on our server-side application. Create **postController.js** file that will allow us to interact with the post table.

Requirements
Class Post:

-     getAllPosts: return all the posts from the post table
-     getPostById: return one post based on the post's id
-     CreatePost: insert a post onto the post table
-     deletePost: deletes a post from the table

**Comment by MohamedSy1** [comment]
We also need to create update post in order to update our post.

**Comment by MohamedSy1** [comment]
Completed all the requirements and added update post controller
