### ISSUE TITLE
Develop basic components of Landing.jsx

### ISSUE THREAD

**Issue by nico-j3** [TenantVoice/TenantVoice#32]
## Context
****
In ```frontend/src/pages``` create a file called```Landing.jsx```. This ```Landing``` component will be rendered in the ```/``` URL endpoint. Currently the ```Home.jsx``` is being rendered at the base route ```/```, so change the endpoint for ```Home.jsx``` to ```/home```. ```Landing.jsx``` needs to return jsx for the header, an image, text that tells the user about our mission and our user-audience

**Requirements**
- [x] ```h1``` for the title of our project "TenantVoice
- [x] An image that gives the user a sense of who we are and what our application is about. This will be displayed in CSS as a ```background-image``` property 

- [x] There will be card components imported from the ```components``` folder to display overviews to the user background info about the problem our users face, our mission, and how users can use this application to solve the problem 

![Image](https://github.com/TenantVoice/TenantVoice/assets/145805241/24efc064-b5f4-4167-b473-526d799b6c5f)

**Comment by nico-j3** [comment]
![Image](https://github.com/TenantVoice/TenantVoice/assets/146131193/52bd9aa3-86f8-43a9-be67-55de09afda25)

**Comment by MohamedSy1** [comment]
@roenc576 pls add description

**Comment by roenc576** [comment]
@MohamedSy1 Added context, requirements and an image for this ticket

**Comment by roenc576** [comment]
Added the name of the file required for this ticket in the ticket's title
