### ISSUE TITLE
Add Tailwind styling to ReportForm.jsx and Home.jsx component

### ISSUE THREAD

**Issue by roenc576** [TenantVoice/TenantVoice#57]
## Context
*****
Currently, the ```post``` cards in ```Home.jsx``` and ```ReportFrom``` in ```ReportForm.jsx``` are difficult to look at and read because of padding, margin, and centering issues. Add styling to ```Home``` and ```ReportForm``` to make all the components more intuitive to the end-user. 

**Requirements**
- [ ] Use [this Tailwind sidebar component](https://flowbite.com/docs/components/sidebar/) that Mohamed found to use as a model for the ```ReportForm``` styling

![Image](https://github.com/TenantVoice/TenantVoice/assets/145805241/abecee9f-d77c-4dba-8330-ef0546b94b43)

**Comment by MohamedSy1** [comment]
Completed the side bar form.
